#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "kanbun_parser.y".
#

require 'racc/parser.rb'

require 'strscan'

class KanbunParser < Racc::Parser

module_eval(<<'...end kanbun_parser.y/module_eval...', 'kanbun_parser.y', 91)

VERBS = %w[学 読 書 見 聞 知 行 来 食 飲 思 言 得 去 入 出 為 陥 慎 争 賢 有 笑
           植 買 戚 易 施]
NOUNS = %w[人 君 臣 子 民 文 道 国 師 天 地 王 士 物 事 土 寒 言]


def parse(str)
  @tokens = tokenize(str)
  @pos = 0
  do_parse
end

def next_token
  @tokens[@pos].tap { @pos += 1 }
end

def tokenize(str)
  tokens = []
  scanner = StringScanner.new(str)
  until scanner.eos?
    case
      when scanner.scan(/莫如/) then tokens << [:NEG_BU,        '莫如']
      when scanner.scan(/莫若/) then tokens << [:NEG_BU,        '莫若']
      when scanner.scan(/不若/) then tokens << [:NEG_BU,        '不若']
      when scanner.scan(/不如/) then tokens << [:NEG_BU,        '不如']
      when scanner.scan(/与/)   then tokens << [:NEG_BU,        '与']
      when scanner.scan(/寧/)   then tokens << [:NEG_BU,        '寧']
      when scanner.scan(/況/)   then tokens << [:NEG_FU,        '況']
      when scanner.scan(/不/)   then tokens << [:NEG_FU,        '不']
      when scanner.scan(/弗/)   then tokens << [:NEG_FU,        '弗']
      when scanner.scan(/非/)   then tokens << [:NEG_HI,        '非']
      when scanner.scan(/無/)   then tokens << [:NEG_MU,        '無']
      when scanner.scan(/莫/)   then tokens << [:NEG_BAKU,      '莫']
      when scanner.scan(/勿/)   then tokens << [:PROHIBIT_NAKA, '勿']
      when scanner.scan(/必/)   then tokens << [:HITSZU,        '必']
      when scanner.scan(/常/)   then tokens << [:JOU,           '常']
      when scanner.scan(/復/)   then tokens << [:MATA,          '復']
      when scanner.scan(Regexp.new("[#{VERBS.join}]")) then tokens << [:VERB, scanner.matched]
      when scanner.scan(Regexp.new("[#{NOUNS.join}]")) then tokens << [:NOUN, scanner.matched]
    else scanner.getch
    end
  end
  tokens << [false, nil]
  tokens
end

...end kanbun_parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    13,    14,    12,    11,    15,    16,    28,    21,    27,    30,
    32,    33,    34,    19,    20,    41,    17,    18,    17,    18,
    17,    18,    17,    18,    44,    17,    18,    22,    23,    24,
    25,    17,    18,    26,    17,    18,    40,    39,    17,    18,
    17,    18,    17,    18,    17,    18,    17,    18,    17,    18,
    17,    18,    17,    18,    17,    18,    17,    18,    17,    18,
    17,    18,    17,    18,    17,    18,    17,    18,    56,    57 ]

racc_action_check = [
     0,     0,     0,     0,     0,     0,    11,     1,    11,    12,
    13,    13,    13,     0,     0,    18,     0,     0,    14,    14,
    13,    13,    11,    11,    21,    12,    12,    10,    10,    10,
    10,    15,    15,    10,    16,    16,    17,    17,    19,    19,
    20,    20,    22,    22,    23,    23,    24,    24,    25,    25,
    26,    26,    27,    27,    28,    28,    30,    30,    32,    32,
    33,    33,    34,    34,    56,    56,    57,    57,    42,    43 ]

racc_action_pointer = [
    -2,     7,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    16,     4,     7,     2,     0,    13,    16,    18,    -4,    20,
    22,    24,    24,    26,    28,    30,    32,    34,    36,   nil,
    38,   nil,    40,    42,    44,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    52,    64,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    46,    48,   nil,   nil ]

racc_action_default = [
   -34,   -34,    -1,    -2,    -3,    -4,    -5,    -6,    -7,    -8,
    -9,   -34,   -34,   -34,   -34,   -34,   -34,   -22,   -25,   -34,
   -34,   -34,   -34,   -34,   -34,   -34,   -34,   -34,   -34,   -19,
   -34,   -18,   -34,   -34,   -34,   -16,   -17,   -20,   -21,   -23,
   -24,   -26,   -34,   -34,    60,   -27,   -28,   -29,   -30,   -33,
   -10,   -11,   -12,   -13,   -14,   -15,   -34,   -34,   -31,   -32 ]

racc_goto_table = [
    10,     1,     2,     3,     4,     5,     6,     7,     8,     9,
   nil,    29,    31,    35,    36,    37,    38,   nil,   nil,    42,
    43,   nil,    45,    46,    47,    48,    49,    50,    51,   nil,
    52,   nil,    53,    54,    55,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    58,    59 ]

racc_goto_check = [
    10,     1,     2,     3,     4,     5,     6,     7,     8,     9,
   nil,    10,    10,    10,    10,    10,    10,   nil,   nil,    10,
    10,   nil,    10,    10,    10,    10,    10,    10,    10,   nil,
    10,   nil,    10,    10,    10,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    10,    10 ]

racc_goto_pointer = [
   nil,     1,     2,     3,     4,     5,     6,     7,     8,     9,
     0 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 21, :_reduce_1,
  1, 22, :_reduce_2,
  1, 22, :_reduce_3,
  1, 22, :_reduce_4,
  1, 22, :_reduce_5,
  1, 22, :_reduce_6,
  1, 22, :_reduce_7,
  1, 22, :_reduce_8,
  1, 22, :_reduce_9,
  3, 23, :_reduce_10,
  3, 23, :_reduce_11,
  3, 23, :_reduce_12,
  3, 24, :_reduce_13,
  3, 24, :_reduce_14,
  3, 24, :_reduce_15,
  2, 28, :_reduce_16,
  2, 28, :_reduce_17,
  2, 28, :_reduce_18,
  2, 28, :_reduce_19,
  2, 28, :_reduce_20,
  2, 29, :_reduce_21,
  1, 30, :_reduce_22,
  2, 30, :_reduce_23,
  2, 30, :_reduce_24,
  1, 30, :_reduce_25,
  2, 30, :_reduce_26,
  3, 25, :_reduce_27,
  3, 25, :_reduce_28,
  3, 25, :_reduce_29,
  3, 25, :_reduce_30,
  4, 26, :_reduce_31,
  4, 26, :_reduce_32,
  3, 27, :_reduce_33 ]

racc_reduce_n = 34

racc_shift_n = 60

racc_token_table = {
  false => 0,
  :error => 1,
  :NEG_BU => 2,
  :NEG_FU => 3,
  :NEG_HI => 4,
  :NEG_MU => 5,
  :NEG_BAKU => 6,
  :PROHIBIT_NAKA => 7,
  :HITSZU => 8,
  :JOU => 9,
  :MATA => 10,
  :MOKU_NAKU => 11,
  :MOKU_SHIKA => 12,
  :FUSHIKA => 13,
  :FUNYUU => 14,
  :YO_NIMO => 15,
  :NAMU => 16,
  :IWA_N_YA => 17,
  :VERB => 18,
  :NOUN => 19 }

racc_nt_base = 20

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "NEG_BU",
  "NEG_FU",
  "NEG_HI",
  "NEG_MU",
  "NEG_BAKU",
  "PROHIBIT_NAKA",
  "HITSZU",
  "JOU",
  "MATA",
  "MOKU_NAKU",
  "MOKU_SHIKA",
  "FUSHIKA",
  "FUNYUU",
  "YO_NIMO",
  "NAMU",
  "IWA_N_YA",
  "VERB",
  "NOUN",
  "$start",
  "sentence",
  "clause",
  "double_neg_clause",
  "partial_neg_clause",
  "compare_clause",
  "select_clause",
  "suppress_clause",
  "neg_clause",
  "prohibit_clause",
  "verb_phrase" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'kanbun_parser.y', 15)
  def _reduce_1(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 18)
  def _reduce_2(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 19)
  def _reduce_3(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 20)
  def _reduce_4(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 21)
  def _reduce_5(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 22)
  def _reduce_6(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 23)
  def _reduce_7(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 24)
  def _reduce_8(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 25)
  def _reduce_9(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 32)
  def _reduce_10(val, _values, result)
     result = "無非#{val[2]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 33)
  def _reduce_11(val, _values, result)
     result = "無不#{val[2]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 34)
  def _reduce_12(val, _values, result)
     result = "非不#{val[2]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 41)
  def _reduce_13(val, _values, result)
     result = "不必#{val[2]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 42)
  def _reduce_14(val, _values, result)
     result = "不常#{val[2]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 43)
  def _reduce_15(val, _values, result)
     result = "不復#{val[2]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 47)
  def _reduce_16(val, _values, result)
     result = "不#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 48)
  def _reduce_17(val, _values, result)
     result = "弗#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 49)
  def _reduce_18(val, _values, result)
     result = "非#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 50)
  def _reduce_19(val, _values, result)
     result = "無#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 51)
  def _reduce_20(val, _values, result)
     result = "莫#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 55)
  def _reduce_21(val, _values, result)
     result = "勿#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 59)
  def _reduce_22(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 60)
  def _reduce_23(val, _values, result)
     result = "#{val[0]}#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 61)
  def _reduce_24(val, _values, result)
     result = "#{val[0]}#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 62)
  def _reduce_25(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 63)
  def _reduce_26(val, _values, result)
     result = "#{val[0]}#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 68)
  def _reduce_27(val, _values, result)
     result = "#{val[0]}莫如#{val[2]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 69)
  def _reduce_28(val, _values, result)
     result = "#{val[0]}莫若#{val[2]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 70)
  def _reduce_29(val, _values, result)
     result = "#{val[0]}不若#{val[2]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 71)
  def _reduce_30(val, _values, result)
     result = "#{val[0]}不如#{val[2]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 76)
  def _reduce_31(val, _values, result)
     result = "与#{val[1]寧{val[3]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 77)
  def _reduce_32(val, _values, result)
     result = "寧#{val[1]無{val[3]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 82)
  def _reduce_33(val, _values, result)
     result = "#{val[0]}況#{val[2]乎}"
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class KanbunParser


if __FILE__ == $0
  parser = KanbunParser.new

  tests = [
    # フェーズ1（回帰テスト）
    ["不学",   "不学"],
    ["不読書", "不読書"],
    ["莫笑",   "莫笑"],
    # フェーズ2a：二重否定
    ["無非王土", "無非王土"],   # 王の土地でないものはない
    ["無不陥",   "無不陥"],     # 陥さないものはない
    ["非不慎",   "非不慎"],     # 慎まないのではない
    # フェーズ2a：部分否定
    ["不必賢",   "不必賢"],     # 必ずしも賢いわけではない
    ["不常有",   "不常有"],     # いつもあるとは限らない
    ["不復得",   "不復得"],     # 二度と得られない
     フェーズ2b：
    ["計莫如植",   "計莫如植"],
    ["地不若人",   "地不若人"],
    ["与易寧戚",   "与易寧戚"],
    ["寧為無為",   "寧為無為"],
    ["馬況人乎",   "馬況人乎"], 
  ]

  tests.each do |input, expected|
    result = parser.parse(input)
    status = result == expected ? "OK" : "NG（期待:#{expected}）"
    puts "#{input} => #{result}  #{status}"
  rescue => e
    puts "#{input} => エラー: #{e.message}"
  end
end
