#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "kanbun_parser.y".
#

require 'racc/parser.rb'

require 'strscan'

class KanbunParser < Racc::Parser

module_eval(<<'...end kanbun_parser.y/module_eval...', 'kanbun_parser.y', 58)

# ============================================================
# 語彙辞書
# PDFの句法一覧 no.1〜9 の例文に登場する字を収録
# （フェーズ1対象範囲：否定・禁止の基本句法）
# ============================================================

VERBS = %w[
  学 読 書 見 聞 知 行 来 食 飲 思 言 得 去 入 出 為
  能 足 笑 施 敢
]
# 追加字の根拠（PDFの句法一覧より）:
#   能 → no.2「弗能応也」
#   足 → no.5「蛇固無足」
#   笑 → no.7「君莫笑」
#   施 → no.8「勿施於人」
#   敢 → no.9「子無敢食我也」（助動詞扱い、VERB+VERBで「敢食」と連結）

NOUNS = %w[
  人 君 臣 子 民 文 道 国 師 天 地 王 士 物 事
  願
]
# 追加字の根拠:
#   願 → no.4「富貴非吾願」
# ※吾（代名詞）は意図的に未収録:
#   テストケース「非吾願」で 吾 をスキップ → 「非願」を返すのが期待動作

def parse(str)
  @tokens = tokenize(str)
  @pos = 0
  do_parse
end

def next_token
  @tokens[@pos].tap { @pos += 1 }
end

def tokenize(str)
  tokens = []
  scanner = StringScanner.new(str)
  # 否定・禁止字の判定を VERBS/NOUNS より先に行う
  until scanner.eos?
    case
    when scanner.scan(/不/) then tokens << [:NEG_BU,        '不']
    when scanner.scan(/弗/) then tokens << [:NEG_FU,        '弗']
    when scanner.scan(/非/) then tokens << [:NEG_HI,        '非']
    when scanner.scan(/無/) then tokens << [:NEG_MU,        '無']
    when scanner.scan(/莫/) then tokens << [:NEG_BAKU,      '莫']
    when scanner.scan(/勿/) then tokens << [:PROHIBIT_NAKA, '勿']
    when scanner.scan(Regexp.new("[#{VERBS.join}]")) then tokens << [:VERB, scanner.matched]
    when scanner.scan(Regexp.new("[#{NOUNS.join}]")) then tokens << [:NOUN, scanner.matched]
    else scanner.getch  # 辞書未登録の字はスキップ
    end
  end
  tokens << [false, nil]
  tokens
end

...end kanbun_parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     6,     7,     8,     9,    10,    11,    12,    13,    12,    13,
    12,    13,    12,    13,    12,    13,    12,    13,    12,    13,
    22,    21,    14,    23 ]

racc_action_check = [
     0,     0,     0,     0,     0,     0,     0,     0,     6,     6,
     7,     7,     8,     8,     9,     9,    10,    10,    11,    11,
    12,    12,     1,    14 ]

racc_action_pointer = [
    -2,    22,   nil,   nil,   nil,   nil,     0,     2,     4,     6,
     8,    10,    12,   nil,    23,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil ]

racc_action_default = [
   -15,   -15,    -1,    -2,    -3,    -4,   -15,   -15,   -15,   -15,
   -15,   -15,   -11,   -14,   -15,    -5,    -6,    -7,    -8,    -9,
   -10,   -12,   -13,    24 ]

racc_goto_table = [
     5,     1,     2,     3,     4,   nil,    15,    16,    17,    18,
    19,    20 ]

racc_goto_check = [
     5,     1,     2,     3,     4,   nil,     5,     5,     5,     5,
     5,     5 ]

racc_goto_pointer = [
   nil,     1,     2,     3,     4,     0 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 11, :_reduce_1,
  1, 12, :_reduce_2,
  1, 12, :_reduce_3,
  1, 12, :_reduce_4,
  2, 13, :_reduce_5,
  2, 13, :_reduce_6,
  2, 13, :_reduce_7,
  2, 13, :_reduce_8,
  2, 13, :_reduce_9,
  2, 14, :_reduce_10,
  1, 15, :_reduce_11,
  2, 15, :_reduce_12,
  2, 15, :_reduce_13,
  1, 15, :_reduce_14 ]

racc_reduce_n = 15

racc_shift_n = 24

racc_token_table = {
  false => 0,
  :error => 1,
  :NEG_BU => 2,
  :NEG_FU => 3,
  :NEG_HI => 4,
  :NEG_MU => 5,
  :NEG_BAKU => 6,
  :PROHIBIT_NAKA => 7,
  :VERB => 8,
  :NOUN => 9 }

racc_nt_base = 10

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "NEG_BU",
  "NEG_FU",
  "NEG_HI",
  "NEG_MU",
  "NEG_BAKU",
  "PROHIBIT_NAKA",
  "VERB",
  "NOUN",
  "$start",
  "sentence",
  "clause",
  "neg_clause",
  "prohibit_clause",
  "verb_phrase" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'kanbun_parser.y', 15)
  def _reduce_1(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 18)
  def _reduce_2(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 19)
  def _reduce_3(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 20)
  def _reduce_4(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 31)
  def _reduce_5(val, _values, result)
     result = "不#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 32)
  def _reduce_6(val, _values, result)
     result = "弗#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 33)
  def _reduce_7(val, _values, result)
     result = "非#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 34)
  def _reduce_8(val, _values, result)
     result = "無#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 35)
  def _reduce_9(val, _values, result)
     result = "莫#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 41)
  def _reduce_10(val, _values, result)
     result = "勿#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 46)
  def _reduce_11(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 47)
  def _reduce_12(val, _values, result)
     result = "#{val[0]}#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 48)
  def _reduce_13(val, _values, result)
     result = "#{val[0]}#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 49)
  def _reduce_14(val, _values, result)
     result = val[0]
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class KanbunParser


if __FILE__ == $0
  parser = KanbunParser.new

  # ============================================================
  # フェーズ1 テストケース
  # PDFの句法一覧 no.1〜9 に対応
  # ============================================================
  tests = [
    # [入力,      期待出力,  句法,        備考]
    ['不学',   '不学',   '否定・不', '動詞単体（no.1）'],
    ['不読書', '不読書', '否定・不', '動詞+名詞（no.1）'],
    ['不知道', '不知道', '否定・不', '動詞+名詞（no.1）'],
    ['弗能',   '弗能',   '否定・弗', '能を追加（no.2）'],
    ['非吾願', '非願',   '否定・非', '吾はスキップ、願はNOUN（no.4）'],
    ['無足',   '無足',   '否定・無', '足を追加（no.5）'],
    ['莫笑',   '莫笑',   '禁止・莫', '笑を追加、出力は否定句法と同形（no.7）'],
    ['勿施',   '勿施',   '禁止・勿', '施を追加（no.8）'],
    ['無敢食', '無敢食', '禁止・無', '敢を追加、VERB+VERBで連結（no.9）'],
    ['見人',   '見人',   '動詞句',   '否定なし'],
    ['知道',   '知道',   '動詞句',   '否定なし'],
  ]

  pass_count = 0
  fail_count = 0

  tests.each do |input, expected, kokuho, note|
    begin
      result = parser.parse(input)
      if result == expected
        pass_count += 1
        puts "PASS  #{input.ljust(5)} => #{result.ljust(6)}  [#{kokuho}] #{note}"
      else
        fail_count += 1
        puts "FAIL  #{input.ljust(5)} => #{result.ljust(6)}  期待: #{expected}  [#{kokuho}] #{note}"
      end
    rescue => e
      fail_count += 1
      puts "ERR   #{input.ljust(5)} => #{e.message}  [#{kokuho}] #{note}"
    end
  end

  puts "\n#{pass_count}/#{tests.size} passed" + (fail_count > 0 ? "  (#{fail_count} failed)" : '')
end
