#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "kanbun_parser.y".
#

require 'racc/parser.rb'

require 'strscan'

class KanbunParser < Racc::Parser

module_eval(<<'...end kanbun_parser.y/module_eval...', 'kanbun_parser.y', 63)

VERBS = %w[学 読 書 見 聞 知 行 来 食 飲 思 言 得 去 入 出 為 陥 慎 争 賢 有 笑]
NOUNS = %w[人 君 臣 子 民 文 道 国 師 天 地 王 士 物 事 土 寒 言]

def parse(str)
  @tokens = tokenize(str)
  @pos = 0
  do_parse
end

def next_token
  @tokens[@pos].tap { @pos += 1 }
end

def tokenize(str)
  tokens = []
  scanner = StringScanner.new(str)
  until scanner.eos?
    case
    when scanner.scan(/不/) then tokens << [:NEG_BU,        '不']
    when scanner.scan(/弗/) then tokens << [:NEG_FU,        '弗']
    when scanner.scan(/非/) then tokens << [:NEG_HI,        '非']
    when scanner.scan(/無/) then tokens << [:NEG_MU,        '無']
    when scanner.scan(/莫/) then tokens << [:NEG_BAKU,      '莫']
    when scanner.scan(/勿/) then tokens << [:PROHIBIT_NAKA, '勿']
    when scanner.scan(/必/) then tokens << [:HITSZU,        '必']
    when scanner.scan(/常/) then tokens << [:JOU,           '常']
    when scanner.scan(/復/) then tokens << [:MATA,          '復']
    when scanner.scan(Regexp.new("[#{VERBS.join}]")) then tokens << [:VERB, scanner.matched]
    when scanner.scan(Regexp.new("[#{NOUNS.join}]")) then tokens << [:NOUN, scanner.matched]
    else scanner.getch
    end
  end
  tokens << [false, nil]
  tokens
end

...end kanbun_parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    10,    11,     9,     8,    12,    13,    18,    16,    17,    14,
    15,    20,    14,    15,    31,    14,    15,    14,    15,    32,
    14,    15,    22,    23,    24,    14,    15,    14,    15,    30,
    29,    14,    15,    14,    15,    14,    15,    14,    15,    14,
    15,    14,    15 ]

racc_action_check = [
     0,     0,     0,     0,     0,     0,     8,     1,     8,     0,
     0,     9,    11,    11,    15,     8,     8,    12,    12,    16,
     9,     9,    10,    10,    10,    10,    10,    13,    13,    14,
    14,    17,    17,    18,    18,    20,    20,    22,    22,    23,
    23,    24,    24 ]

racc_action_pointer = [
    -2,     7,   nil,   nil,   nil,   nil,   nil,   nil,     4,     9,
    14,     1,     6,    16,    18,     2,    19,    20,    22,   nil,
    24,   nil,    26,    28,    30,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
   -24,   -24,    -1,    -2,    -3,    -4,    -5,    -6,   -24,   -24,
   -24,   -24,   -24,   -24,   -19,   -22,   -24,   -24,   -24,   -16,
   -24,   -15,   -24,   -24,   -24,   -13,   -14,   -17,   -18,   -20,
   -21,   -23,    39,    -7,    -8,    -9,   -10,   -11,   -12 ]

racc_goto_table = [
     7,     1,     2,     3,     4,     5,     6,   nil,    19,    21,
    25,    26,    27,    28,   nil,   nil,   nil,    33,    34,   nil,
    35,   nil,    36,    37,    38 ]

racc_goto_check = [
     7,     1,     2,     3,     4,     5,     6,   nil,     7,     7,
     7,     7,     7,     7,   nil,   nil,   nil,     7,     7,   nil,
     7,   nil,     7,     7,     7 ]

racc_goto_pointer = [
   nil,     1,     2,     3,     4,     5,     6,     0 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 14, :_reduce_1,
  1, 15, :_reduce_2,
  1, 15, :_reduce_3,
  1, 15, :_reduce_4,
  1, 15, :_reduce_5,
  1, 15, :_reduce_6,
  3, 16, :_reduce_7,
  3, 16, :_reduce_8,
  3, 16, :_reduce_9,
  3, 17, :_reduce_10,
  3, 17, :_reduce_11,
  3, 17, :_reduce_12,
  2, 18, :_reduce_13,
  2, 18, :_reduce_14,
  2, 18, :_reduce_15,
  2, 18, :_reduce_16,
  2, 18, :_reduce_17,
  2, 19, :_reduce_18,
  1, 20, :_reduce_19,
  2, 20, :_reduce_20,
  2, 20, :_reduce_21,
  1, 20, :_reduce_22,
  2, 20, :_reduce_23 ]

racc_reduce_n = 24

racc_shift_n = 39

racc_token_table = {
  false => 0,
  :error => 1,
  :NEG_BU => 2,
  :NEG_FU => 3,
  :NEG_HI => 4,
  :NEG_MU => 5,
  :NEG_BAKU => 6,
  :PROHIBIT_NAKA => 7,
  :HITSZU => 8,
  :JOU => 9,
  :MATA => 10,
  :VERB => 11,
  :NOUN => 12 }

racc_nt_base = 13

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "NEG_BU",
  "NEG_FU",
  "NEG_HI",
  "NEG_MU",
  "NEG_BAKU",
  "PROHIBIT_NAKA",
  "HITSZU",
  "JOU",
  "MATA",
  "VERB",
  "NOUN",
  "$start",
  "sentence",
  "clause",
  "double_neg_clause",
  "partial_neg_clause",
  "neg_clause",
  "prohibit_clause",
  "verb_phrase" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'kanbun_parser.y', 10)
  def _reduce_1(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 13)
  def _reduce_2(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 14)
  def _reduce_3(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 15)
  def _reduce_4(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 16)
  def _reduce_5(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 17)
  def _reduce_6(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 24)
  def _reduce_7(val, _values, result)
     result = "無非#{val[2]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 25)
  def _reduce_8(val, _values, result)
     result = "無不#{val[2]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 26)
  def _reduce_9(val, _values, result)
     result = "非不#{val[2]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 33)
  def _reduce_10(val, _values, result)
     result = "不必#{val[2]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 34)
  def _reduce_11(val, _values, result)
     result = "不常#{val[2]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 35)
  def _reduce_12(val, _values, result)
     result = "不復#{val[2]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 39)
  def _reduce_13(val, _values, result)
     result = "不#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 40)
  def _reduce_14(val, _values, result)
     result = "弗#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 41)
  def _reduce_15(val, _values, result)
     result = "非#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 42)
  def _reduce_16(val, _values, result)
     result = "無#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 43)
  def _reduce_17(val, _values, result)
     result = "莫#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 47)
  def _reduce_18(val, _values, result)
     result = "勿#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 51)
  def _reduce_19(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 52)
  def _reduce_20(val, _values, result)
     result = "#{val[0]}#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 53)
  def _reduce_21(val, _values, result)
     result = "#{val[0]}#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 54)
  def _reduce_22(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'kanbun_parser.y', 55)
  def _reduce_23(val, _values, result)
     result = "#{val[0]}#{val[1]}"
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class KanbunParser


if __FILE__ == $0
  parser = KanbunParser.new

  tests = [
    # フェーズ1（回帰テスト）
    ["不学",   "不学"],
    ["不読書", "不読書"],
    ["莫笑",   "莫笑"],
    # フェーズ2a：二重否定
    ["無非王土", "無非王土"],   # 王の土地でないものはない
    ["無不陥",   "無不陥"],     # 陥さないものはない
    ["非不慎",   "非不慎"],     # 慎まないのではない
    # フェーズ2a：部分否定
    ["不必賢",   "不必賢"],     # 必ずしも賢いわけではない
    ["不常有",   "不常有"],     # いつもあるとは限らない
    ["不復得",   "不復得"],     # 二度と得られない
  ]

  tests.each do |input, expected|
    result = parser.parse(input)
    status = result == expected ? "OK" : "NG（期待:#{expected}）"
    puts "#{input} => #{result}  #{status}"
  rescue => e
    puts "#{input} => エラー: #{e.message}"
  end
end
